name: simple_news
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  dio: ^4.0.4
  get_it: ^7.2.0
  injectable: ^1.5.2
  freezed_annotation: ^1.1.0
  cached_network_image: ^3.2.0
  infinite_scroll_pagination: ^3.1.0
  flutter_bloc: ^8.0.1
  fpdart: ^0.0.13
  rxdart: ^0.27.3
  intl: ^0.17.0
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  build_runner: ^2.1.7
  freezed: ^1.1.0
  json_serializable: ^6.1.4
  injectable_generator: ^1.5.2
  mockito: ^5.0.17
  bloc_test: ^9.0.2

flutter:
  uses-material-design: true
