// Mocks generated by Mockito 5.0.17 from annotations
// in simple_news/test/presentation/pages/home/cubit/home_cubit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:fpdart/fpdart.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:simple_news/domain/core/result/failure.dart' as _i7;
import 'package:simple_news/domain/model/article.dart' as _i4;
import 'package:simple_news/domain/repository/my_repository.dart' as _i2;
import 'package:simple_news/domain/usecase/fetch_news_usecase.dart' as _i5;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeMyRepository_0 extends _i1.Fake implements _i2.MyRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

class _FakeSource_2 extends _i1.Fake implements _i4.Source {}

class _Fake$ArticleCopyWith_3<$Res> extends _i1.Fake
    implements _i4.$ArticleCopyWith<$Res> {}

/// A class which mocks [FetchNewsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchNewsUseCase extends _i1.Mock implements _i5.FetchNewsUseCase {
  MockFetchNewsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MyRepository get myRepository =>
      (super.noSuchMethod(Invocation.getter(#myRepository),
          returnValue: _FakeMyRepository_0()) as _i2.MyRepository);
  @override
  _i6.Future<_i3.Either<_i7.Failure, List<_i4.Article>>> execute(
          _i5.FetchNewsUseCaseParams? param) =>
      (super.noSuchMethod(Invocation.method(#execute, [param]),
          returnValue: Future<_i3.Either<_i7.Failure, List<_i4.Article>>>.value(
              _FakeEither_1<_i7.Failure, List<_i4.Article>>())) as _i6
          .Future<_i3.Either<_i7.Failure, List<_i4.Article>>>);
  @override
  _i6.Future<_i3.Either<_i7.Failure, List<_i4.Article>>> call(
          _i5.FetchNewsUseCaseParams? param) =>
      (super.noSuchMethod(Invocation.method(#call, [param]),
          returnValue: Future<_i3.Either<_i7.Failure, List<_i4.Article>>>.value(
              _FakeEither_1<_i7.Failure, List<_i4.Article>>())) as _i6
          .Future<_i3.Either<_i7.Failure, List<_i4.Article>>>);
}

/// A class which mocks [Article].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticle extends _i1.Mock implements _i4.Article {
  MockArticle() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Source get source => (super.noSuchMethod(Invocation.getter(#source),
      returnValue: _FakeSource_2()) as _i4.Source);
  @override
  String get author =>
      (super.noSuchMethod(Invocation.getter(#author), returnValue: '')
          as String);
  @override
  String get title =>
      (super.noSuchMethod(Invocation.getter(#title), returnValue: '')
          as String);
  @override
  String get description =>
      (super.noSuchMethod(Invocation.getter(#description), returnValue: '')
          as String);
  @override
  String get url =>
      (super.noSuchMethod(Invocation.getter(#url), returnValue: '') as String);
  @override
  String get urlToImage =>
      (super.noSuchMethod(Invocation.getter(#urlToImage), returnValue: '')
          as String);
  @override
  String get publishedAt =>
      (super.noSuchMethod(Invocation.getter(#publishedAt), returnValue: '')
          as String);
  @override
  String get content =>
      (super.noSuchMethod(Invocation.getter(#content), returnValue: '')
          as String);
  @override
  _i4.$ArticleCopyWith<_i4.Article> get copyWith =>
      (super.noSuchMethod(Invocation.getter(#copyWith),
              returnValue: _Fake$ArticleCopyWith_3<_i4.Article>())
          as _i4.$ArticleCopyWith<_i4.Article>);
}
